package events

import "time"

// EventType describes the kind of mutation a synchronization event carries.
type EventType string

const (
	EventCreated EventType = "created"
	EventUpdated EventType = "updated"
	EventDeleted EventType = "deleted"
)

// Provenance identifies the origin of a change so the engine can recognize
// events generated by its own synchronization operations and prevent loops.
type Provenance struct {
	OriginSource    string `json:"origin_source,omitempty"`
	OriginEventID   string `json:"origin_event_id,omitempty"`
	SyncOperationID string `json:"sync_operation_id,omitempty"`

	// ResolvedConflictID marks a synthetic event produced by an operator
	// resolving a conflict: the worker applies the chosen side without
	// re-running conflict detection (or ordering/loop checks) on it.
	ResolvedConflictID string `json:"resolved_conflict_id,omitempty"`

	// ReconcileFindingID marks a synthetic event produced by the reconciliation
	// engine (or an operator approving a manual finding): the worker applies the
	// finding's chosen repair direction directly, without re-running conflict,
	// ordering, or loop checks.
	ReconcileFindingID string `json:"reconcile_finding_id,omitempty"`
}

// Event is the canonical synchronization event. Events are immutable: once
// produced they are never mutated. The payload holds provider-native fields.
// The JSON contract is stable snake_case, shared with any consumer.
type Event struct {
	EventID    string    `json:"event_id"`
	TenantID   string    `json:"tenant_id"`
	Source     string    `json:"source"`
	EntityType string    `json:"entity_type"`
	EntityID   string    `json:"entity_id"`
	EventType  EventType `json:"event_type"`

	// SourceVersion is the provider's version number for the entity at the
	// time the event was emitted. Used for ordering and stale-event rejection.
	SourceVersion int64     `json:"source_version"`
	OccurredAt    time.Time `json:"occurred_at"`
	ReceivedAt    time.Time `json:"received_at"`
	CorrelationID string    `json:"correlation_id,omitempty"`

	Provenance Provenance `json:"provenance,omitempty"`

	Payload map[string]any `json:"payload"`
}

// Key returns the deterministic idempotency key for this event.
// tenant_id + source + event_id uniquely identifies a logical event.
func (e *Event) Key() (tenant, source, eventID string) {
	return e.TenantID, e.Source, e.EventID
}

// Topic is the Redpanda partition key: per-entity ordering, cross-entity
// parallelism.
func (e *Event) PartitionKey() string {
	return e.TenantID + ":" + e.EntityType + ":" + e.EntityID
}
