package events

import "time"

// EventType describes the kind of mutation a synchronization event carries.
type EventType string

const (
	EventCreated EventType = "created"
	EventUpdated EventType = "updated"
	EventDeleted EventType = "deleted"
)

// Provenance identifies the origin of a change so the engine can recognize
// events generated by its own synchronization operations and prevent loops.
type Provenance struct {
	OriginSource    string `json:"origin_source,omitempty"`
	OriginEventID   string `json:"origin_event_id,omitempty"`
	SyncOperationID string `json:"sync_operation_id,omitempty"`
}

// Event is the canonical synchronization event. Events are immutable: once
// produced they are never mutated. The payload holds provider-native fields.
type Event struct {
	EventID    string
	TenantID   string
	Source     string
	EntityType string
	EntityID   string
	EventType  EventType

	// SourceVersion is the provider's version number for the entity at the
	// time the event was emitted. Used for ordering and stale-event rejection.
	SourceVersion int64

	OccurredAt    time.Time
	ReceivedAt    time.Time
	CorrelationID string

	Provenance Provenance

	Payload map[string]any
}

// Key returns the deterministic idempotency key for this event.
// tenant_id + source + event_id uniquely identifies a logical event.
func (e *Event) Key() (tenant, source, eventID string) {
	return e.TenantID, e.Source, e.EventID
}

// Topic is the Redpanda partition key: per-entity ordering, cross-entity
// parallelism.
func (e *Event) PartitionKey() string {
	return e.TenantID + ":" + e.EntityType + ":" + e.EntityID
}
