package simulator

import (
	"sort"
	"sync"
	"time"
)

// Record is an in-memory provider record. Data holds provider-native fields.
type Record struct {
	ID        string
	Version   int64
	UpdatedAt time.Time
	Deleted   bool
	Data      map[string]any
}

// Store is a thread-safe in-memory record store. It is deliberately not
// durable: it simulates an external system's database in local development.
type Store struct {
	mu      sync.RWMutex
	records map[string]*Record
	nextID  int64
}

func NewStore() *Store {
	return &Store{records: make(map[string]*Record)}
}

// SetIDPrefix sets the prefix used for generated ids (e.g. "sf-", "hub-").
func (s *Store) SetIDPrefix(p string) { prefix = p }

// Seed inserts count records generated by newRec. Useful at startup and for
// load testing.
func (s *Store) Seed(count int, newRec func(id string, n int) map[string]any) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for i := 0; i < count; i++ {
		id := s.genID()
		s.records[id] = &Record{
			ID:        id,
			Version:   1,
			UpdatedAt: time.Now().UTC(),
			Data:      newRec(id, i),
		}
	}
}

func (s *Store) genID() string {
	s.nextID++
	return idFormat(s.nextID)
}

func idFormat(n int64) string {
	// provider-style ids, e.g. "sf-000001" / "hub-000001"
	// prefix is set by the caller via SetIDPrefix before use.
	return prefix + pad(n)
}

func pad(n int64) string {
	// zero-padded 6-digit suffix
	const digits = "00000000000000000000"
	s := itoa(n)
	if len(s) < 6 {
		s = digits[:6-len(s)] + s
	}
	return s
}

func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

func (s *Store) List(cursor string, limit int, since time.Time) ([]*Record, string, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	ids := make([]string, 0, len(s.records))
	for id := range s.records {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	start := 0
	if cursor != "" {
		for i, id := range ids {
			if id == cursor {
				start = i + 1
				break
			}
		}
	}

	if limit <= 0 || limit > 1000 {
		limit = 100
	}

	var out []*Record
	next := ""
	rest := ids[start:]
	for _, id := range rest {
		rec := s.records[id]
		if !since.IsZero() && rec.UpdatedAt.Before(since) {
			continue
		}
		out = append(out, cloneRecord(rec))
		if len(out) >= limit {
			// cursor points at the last returned id; the next page starts
			// strictly after it, so no boundary record is skipped
			next = id
			break
		}
	}
	return out, next, next != ""
}

func (s *Store) Get(id string) (*Record, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	rec, ok := s.records[id]
	if !ok {
		return nil, false
	}
	return cloneRecord(rec), true
}

func (s *Store) Insert(data map[string]any) *Record {
	s.mu.Lock()
	defer s.mu.Unlock()
	id := s.genID()
	now := time.Now().UTC()
	rec := &Record{ID: id, Version: 1, UpdatedAt: now, Data: cloneMap(data)}
	s.records[id] = rec
	return cloneRecord(rec)
}

func (s *Store) Update(id string, data map[string]any) (*Record, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	rec, ok := s.records[id]
	if !ok {
		return nil, false
	}
	for k, v := range data {
		rec.Data[k] = v
	}
	rec.Version++
	rec.UpdatedAt = time.Now().UTC()
	return cloneRecord(rec), true
}

func (s *Store) SoftDelete(id string) (*Record, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	rec, ok := s.records[id]
	if !ok {
		return nil, false
	}
	rec.Deleted = true
	rec.Version++
	rec.UpdatedAt = time.Now().UTC()
	rec.Data["deleted"] = true
	return cloneRecord(rec), true
}

func (s *Store) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.records)
}

func (s *Store) All() []*Record {
	s.mu.RLock()
	defer s.mu.RUnlock()
	ids := make([]string, 0, len(s.records))
	for id := range s.records {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	out := make([]*Record, 0, len(ids))
	for _, id := range ids {
		out = append(out, cloneRecord(s.records[id]))
	}
	return out
}

func cloneRecord(r *Record) *Record {
	c := *r
	c.Data = cloneMap(r.Data)
	return &c
}

func cloneMap(m map[string]any) map[string]any {
	out := make(map[string]any, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

var prefix = "sf-"
